FROM python:3.9.18-slim-bullseye

# set TimeZone
# RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 8080
WORKDIR /app
COPY ./ /app/
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/
ENV TG_BOT_TOKEN=""
ENV GOOGLE_GEMINI_KEY=""
CMD ["sh", "-c", "python gemini_telegram_bot.py ${TG_BOT_TOKEN} ${GOOGLE_GEMINI_KEY}"]